/**
 * Database types for Supabase
 * This file will be auto-generated by Supabase CLI once connected
 * For now, we define the expected structure manually
 */

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            users: {
                Row: {
                    id: string
                    email: string
                    full_name: string | null
                    avatar_url: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    email: string
                    full_name?: string | null
                    avatar_url?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    full_name?: string | null
                    avatar_url?: string | null
                    updated_at?: string
                }
            }
            organizations: {
                Row: {
                    id: string
                    name: string
                    team_number: string | null
                    invite_code: string
                    owner_id: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    team_number?: string | null
                    invite_code?: string
                    owner_id: string
                    created_at?: string
                }
                Update: {
                    name?: string
                    team_number?: string | null
                    invite_code?: string
                    owner_id?: string
                }
            }
            subscriptions: {
                Row: {
                    id: string
                    user_id: string
                    stripe_customer_id: string | null
                    stripe_subscription_id: string | null
                    status: 'trialing' | 'active' | 'canceled' | 'past_due' | 'incomplete'
                    plan: 'free' | 'team' | 'organization'
                    current_period_end: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    stripe_customer_id?: string | null
                    stripe_subscription_id?: string | null
                    status?: 'trialing' | 'active' | 'canceled' | 'past_due' | 'incomplete'
                    plan?: 'free' | 'team' | 'organization'
                    current_period_end?: string | null
                    created_at?: string
                }
                Update: {
                    stripe_customer_id?: string | null
                    stripe_subscription_id?: string | null
                    status?: 'trialing' | 'active' | 'canceled' | 'past_due' | 'incomplete'
                    plan?: 'free' | 'team' | 'organization'
                    current_period_end?: string | null
                }
            }
            organization_members: {
                Row: {
                    id: string
                    organization_id: string
                    user_id: string
                    role: 'owner' | 'admin' | 'member'
                    joined_at: string
                }
                Insert: {
                    id?: string
                    organization_id: string
                    user_id: string
                    role?: 'owner' | 'admin' | 'member'
                    joined_at?: string
                }
                Update: {
                    role?: 'owner' | 'admin' | 'member'
                }
            }
            teams: {
                Row: {
                    id: string
                    organization_id: string
                    name: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    organization_id: string
                    name: string
                    created_at?: string
                }
                Update: {
                    name?: string
                }
            }
            team_members: {
                Row: {
                    id: string
                    team_id: string
                    user_id: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    team_id: string
                    user_id: string
                    created_at?: string
                }
                Update: {}
            }
            tasks: {
                Row: {
                    id: string
                    organization_id: string
                    team_id: string | null
                    title: string
                    description: string | null
                    status: 'Backlog' | 'To Do' | 'In Progress' | 'Validation' | 'Done'
                    type: 'Feature' | 'Bug'
                    assigned_to: string | null
                    tags: string[]
                    checklist: Json
                    timeline: Json
                    due_date: string | null
                    created_at: string
                    updated_at: string
                    sync_status: 'synced' | 'pending' | 'conflict'
                }
                Insert: {
                    id?: string
                    organization_id: string
                    team_id?: string | null
                    title: string
                    description?: string | null
                    status?: 'Backlog' | 'To Do' | 'In Progress' | 'Validation' | 'Done'
                    type?: 'Feature' | 'Bug'
                    assigned_to?: string | null
                    tags?: string[]
                    checklist?: Json
                    timeline?: Json
                    due_date?: string | null
                    created_at?: string
                    updated_at?: string
                    sync_status?: 'synced' | 'pending' | 'conflict'
                }
                Update: {
                    team_id?: string | null
                    title?: string
                    description?: string | null
                    status?: 'Backlog' | 'To Do' | 'In Progress' | 'Validation' | 'Done'
                    type?: 'Feature' | 'Bug'
                    assigned_to?: string | null
                    tags?: string[]
                    checklist?: Json
                    timeline?: Json
                    due_date?: string | null
                    updated_at?: string
                    sync_status?: 'synced' | 'pending' | 'conflict'
                }
            }
            checklists: {
                Row: {
                    id: string
                    organization_id: string
                    name: string
                    items: Json
                    is_template: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    organization_id: string
                    name: string
                    items?: Json
                    is_template?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    name?: string
                    items?: Json
                    is_template?: boolean
                    updated_at?: string
                }
            }
            scouting_reports: {
                Row: {
                    id: string
                    organization_id: string
                    opponent_team_number: string
                    match_number: number
                    event_name: string | null
                    data: Json
                    created_by: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    organization_id: string
                    opponent_team_number: string
                    match_number: number
                    event_name?: string | null
                    data?: Json
                    created_by: string
                    created_at?: string
                }
                Update: {
                    opponent_team_number?: string
                    match_number?: number
                    event_name?: string | null
                    data?: Json
                }
            }
            match_plans: {
                Row: {
                    id: string
                    organization_id: string
                    match_number: number | null
                    alliance_team: string | null
                    drawing_data: Json
                    notes: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    organization_id: string
                    match_number?: number | null
                    alliance_team?: string | null
                    drawing_data?: Json
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    match_number?: number | null
                    alliance_team?: string | null
                    drawing_data?: Json
                    notes?: string | null
                    updated_at?: string
                }
            }
        }
        Views: {}
        Functions: {}
        Enums: {}
    }
}

// Helper types for easier usage
export type User = Database['public']['Tables']['users']['Row']
export type Organization = Database['public']['Tables']['organizations']['Row']
export type Subscription = Database['public']['Tables']['subscriptions']['Row']
export type OrganizationMember = Database['public']['Tables']['organization_members']['Row']
export type Team = Database['public']['Tables']['teams']['Row']
export type Task = Database['public']['Tables']['tasks']['Row']
export type Checklist = Database['public']['Tables']['checklists']['Row']
export type ScoutingReport = Database['public']['Tables']['scouting_reports']['Row']
export type MatchPlan = Database['public']['Tables']['match_plans']['Row']
