/**
 * Database types for Supabase
 * This file will be auto-generated by Supabase CLI once connected
 * For now, we define the expected structure manually
 * 
 * ENTITY RENAME (2026-01-05):
 * - organizations → teams
 * - organization_members → team_members
 * - teams → sub_teams
 * - team_members (old sub-team junction) → sub_team_members
 */

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            users: {
                Row: {
                    id: string
                    email: string
                    full_name: string | null
                    avatar_url: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    email: string
                    full_name?: string | null
                    avatar_url?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    full_name?: string | null
                    avatar_url?: string | null
                    updated_at?: string
                }
            }
            // Renamed from 'organizations' - The top-level FTC team
            teams: {
                Row: {
                    id: string
                    name: string
                    team_number: string | null
                    invite_code: string
                    owner_id: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    team_number?: string | null
                    invite_code?: string
                    owner_id: string
                    created_at?: string
                }
                Update: {
                    name?: string
                    team_number?: string | null
                    invite_code?: string
                    owner_id?: string
                }
            }
            subscriptions: {
                Row: {
                    id: string
                    user_id: string
                    stripe_customer_id: string | null
                    stripe_subscription_id: string | null
                    status: 'trialing' | 'active' | 'canceled' | 'past_due' | 'incomplete'
                    plan: 'free' | 'team' | 'organization'
                    current_period_end: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    stripe_customer_id?: string | null
                    stripe_subscription_id?: string | null
                    status?: 'trialing' | 'active' | 'canceled' | 'past_due' | 'incomplete'
                    plan?: 'free' | 'team' | 'organization'
                    current_period_end?: string | null
                    created_at?: string
                }
                Update: {
                    stripe_customer_id?: string | null
                    stripe_subscription_id?: string | null
                    status?: 'trialing' | 'active' | 'canceled' | 'past_due' | 'incomplete'
                    plan?: 'free' | 'team' | 'organization'
                    current_period_end?: string | null
                }
            }
            // Renamed from 'organization_members' - Users who belong to a Team
            team_members: {
                Row: {
                    id: string
                    team_id: string
                    user_id: string
                    role: 'coach' | 'assistant_coach' | 'mentor' | 'student'
                    status: 'pending' | 'approved' | 'removed'
                    is_billing_active: boolean
                    age_13_plus: boolean | null
                    joined_at: string
                }
                Insert: {
                    id?: string
                    team_id: string
                    user_id: string
                    role?: 'coach' | 'assistant_coach' | 'mentor' | 'student'
                    status?: 'pending' | 'approved' | 'removed'
                    is_billing_active?: boolean
                    age_13_plus?: boolean | null
                    joined_at?: string
                }
                Update: {
                    role?: 'coach' | 'assistant_coach' | 'mentor' | 'student'
                    status?: 'pending' | 'approved' | 'removed'
                    is_billing_active?: boolean
                    age_13_plus?: boolean | null
                }
            }
            // Renamed from 'teams' - Working groups within a Team (Build, Programming, etc.)
            sub_teams: {
                Row: {
                    id: string
                    team_id: string
                    season_id: string | null
                    name: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    team_id: string
                    season_id?: string | null
                    name: string
                    created_at?: string
                }
                Update: {
                    name?: string
                    season_id?: string | null
                }
            }
            // Renamed from 'team_members' (old junction) - TeamMember assigned to SubTeam
            sub_team_members: {
                Row: {
                    id: string
                    sub_team_id: string
                    team_member_id: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    sub_team_id: string
                    team_member_id: string
                    created_at?: string
                }
                Update: {}
            }
            seasons: {
                Row: {
                    id: string
                    team_id: string
                    name: string
                    field_image_data: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    team_id: string
                    name: string
                    field_image_data?: string | null
                    created_at?: string
                }
                Update: {
                    name?: string
                    field_image_data?: string | null
                }
            }
            tasks: {
                Row: {
                    id: string
                    team_id: string
                    season_id: string | null
                    sub_team_id: string | null
                    title: string
                    description: string | null
                    status: 'Backlog' | 'To Do' | 'In Progress' | 'Testing' | 'Done'
                    type: 'Feature' | 'Bug'
                    assigned_to: string | null
                    tags: string[]
                    checklist: Json
                    timeline: Json
                    due_date: string | null
                    created_at: string
                    updated_at: string
                    sync_status: 'synced' | 'pending' | 'conflict'
                }
                Insert: {
                    id?: string
                    team_id: string
                    season_id?: string | null
                    sub_team_id?: string | null
                    title: string
                    description?: string | null
                    status?: 'Backlog' | 'To Do' | 'In Progress' | 'Testing' | 'Done'
                    type?: 'Feature' | 'Bug'
                    assigned_to?: string | null
                    tags?: string[]
                    checklist?: Json
                    timeline?: Json
                    due_date?: string | null
                    created_at?: string
                    updated_at?: string
                    sync_status?: 'synced' | 'pending' | 'conflict'
                }
                Update: {
                    sub_team_id?: string | null
                    season_id?: string | null
                    title?: string
                    description?: string | null
                    status?: 'Backlog' | 'To Do' | 'In Progress' | 'Testing' | 'Done'
                    type?: 'Feature' | 'Bug'
                    assigned_to?: string | null
                    tags?: string[]
                    checklist?: Json
                    timeline?: Json
                    due_date?: string | null
                    updated_at?: string
                    sync_status?: 'synced' | 'pending' | 'conflict'
                }
            }
            checklists: {
                Row: {
                    id: string
                    team_id: string
                    season_id: string | null
                    name: string
                    items: Json
                    is_template: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    team_id: string
                    season_id?: string | null
                    name: string
                    items?: Json
                    is_template?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    name?: string
                    items?: Json
                    is_template?: boolean
                    updated_at?: string
                }
            }
            scouting_reports: {
                Row: {
                    id: string
                    team_id: string
                    season_id: string | null
                    opponent_team_number: string
                    match_number: number
                    event_name: string | null
                    data: Json
                    created_by: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    team_id: string
                    season_id?: string | null
                    opponent_team_number: string
                    match_number: number
                    event_name?: string | null
                    data?: Json
                    created_by: string
                    created_at?: string
                }
                Update: {
                    opponent_team_number?: string
                    match_number?: number
                    event_name?: string | null
                    data?: Json
                }
            }
            match_plans: {
                Row: {
                    id: string
                    team_id: string
                    season_id: string | null
                    match_number: number | null
                    alliance_team: string | null
                    drawing_data: Json
                    notes: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    team_id: string
                    season_id?: string | null
                    match_number?: number | null
                    alliance_team?: string | null
                    drawing_data?: Json
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    match_number?: number | null
                    alliance_team?: string | null
                    drawing_data?: Json
                    notes?: string | null
                    updated_at?: string
                }
            }
            // Invites for team joining
            invites: {
                Row: {
                    id: string
                    team_id: string
                    code: string
                    created_by: string
                    expires_at: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    team_id: string
                    code: string
                    created_by: string
                    expires_at?: string | null
                    created_at?: string
                }
                Update: {
                    expires_at?: string | null
                }
            }
            // User legal attestations
            user_attestations: {
                Row: {
                    id: string
                    user_id: string
                    attestation_type: 'terms' | 'privacy' | 'community_guidelines' | 'age_18_plus' | 'coppa_responsibility' | 'billing_acknowledgement' | 'age_13_plus'
                    version: string
                    attested_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    attestation_type: 'terms' | 'privacy' | 'community_guidelines' | 'age_18_plus' | 'coppa_responsibility' | 'billing_acknowledgement' | 'age_13_plus'
                    version?: string
                    attested_at?: string
                }
                Update: {
                    version?: string
                    attested_at?: string
                }
            }
        }
        Views: {}
        Functions: {}
        Enums: {}
    }
}

// Helper types for easier usage
export type User = Database['public']['Tables']['users']['Row']
export type Team = Database['public']['Tables']['teams']['Row']
export type Subscription = Database['public']['Tables']['subscriptions']['Row']
export type TeamMember = Database['public']['Tables']['team_members']['Row']
export type SubTeam = Database['public']['Tables']['sub_teams']['Row']
export type SubTeamMember = Database['public']['Tables']['sub_team_members']['Row']
export type Season = Database['public']['Tables']['seasons']['Row']
export type Task = Database['public']['Tables']['tasks']['Row']
export type Checklist = Database['public']['Tables']['checklists']['Row']
export type ScoutingReport = Database['public']['Tables']['scouting_reports']['Row']
export type MatchPlan = Database['public']['Tables']['match_plans']['Row']
export type Invite = Database['public']['Tables']['invites']['Row']
export type UserAttestation = Database['public']['Tables']['user_attestations']['Row']

